AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Root stack
Parameters:
  SystemName:
    Type: String
    Description: Specify system name. The following constraints applied between 3 - 8 characters, lowercase alphanumeric and use for send it in to User Data init cloud for EC2
    Default: 'mysysname'
  AdminPassword:
    Description: Password for the Administrator for send it in to User Data init cloud for EC2
    Type: String
    Default: 'myPass'
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: myAws_key
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.nano
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
      m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
      c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
      g3.8xlarge,
      r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
      i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
      d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  SecurityGroupName:
    Description: Name of the security group
    Type: String 
    Default: 'sg1'
  SecurityGroupName2:
    Description: Name of the security group2
    Type: String 
    Default: 'sg2'
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  AdditionalEBSVolume:
    Description: The addtional disk size
    Default: 10
    Type: String
  StaticPrivateIP:
    Type: String
    Default: 10.1.10.56
    Description: First instance private IP. This must be a valid IP address for Subnet
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
  StaticPrivateIP2:
    Type: String
    Default: 10.1.20.88
    Description: Second instance private IP. This must be a valid IP address for Subnet
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
  S3BucketLocation:
    Type: String
    Description: Please input the userdata location from s3 example 's3://hui-cloud-aha/bash.sh'
    Default: 's3://hui-cloud-aha/bash.sh'
  S3BucketRegion:
    Type: String
    Description: Input the S3bucket region for example 'us-east-1'
    Default: us-east-1
  UserDataArgument1:
    Type: String
    Description: Please input userdata argument1
  UserDataArgument2:
    Type: String
    Description: Please input userdata argument2
  UserDataArgument3:
    Type: String
    Description: Please input userdata argument3
   
# Resources
# https://nested-bucket2-for-template.s3.eu-west-3.amazonaws.com/fakevpc.yaml
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nested-bucket2-for-template.s3.eu-west-3.amazonaws.com/vpc.yaml
      TimeoutInMinutes: 15
  InstanceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://nested-bucket2-for-template.s3.eu-west-3.amazonaws.com/stack.yaml
      TimeoutInMinutes: 15
      Parameters:
          SystemName: !Ref SystemName
          AdminPassword: !Ref AdminPassword
          SecurityGroupName: !Ref SecurityGroupName
          SecurityGroupName2: !Ref SecurityGroupName2
          UserDataArgument1: !Ref UserDataArgument1
          KeyName: !Ref KeyName
          UserDataArgument2: !Ref UserDataArgument2
          UserDataArgument3: !Ref UserDataArgument3
          S3BucketLocation: !Ref S3BucketLocation

